### ISSUE TITLE
Email IOException

### ISSUE THREAD

**Issue by JoshKeegan** [JoshKeegan/KLog.NET#11]
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException
Stack:
   at System.Net.Sockets.NetworkStream.Read(Byte[], Int32, Int32)
   at System.Net.PooledStream.Read(Byte[], Int32, Int32)
   at System.Net.Mail.SmtpPooledStream.Dispose(Boolean)
   at System.IO.Stream.Close()
   at System.Net.ConnectionPool.Destroy(System.Net.PooledStream)
   at System.Net.ConnectionPool.ForceCleanup()
   at System.Net.ConnectionPoolManager.CleanupConnectionPool(System.Net.ServicePoint, System.String)
   at System.Net.Mail.SmtpClient.Dispose(Boolean)
   at KLog.EmailLog+<>c__DisplayClass1.<write>b__0(System.Object, System.ComponentModel.AsyncCompletedEventArgs)

**Comment by JoshKeegan** [comment]
Speculate that the SmtpClient.Dispose Method could potentially throw an IOException, since docs (https://msdn.microsoft.com/en-us/library/ee706941%28v=vs.110%29.aspx) say it sends a QUIT message to the SMTP server (which could go wrong).
