### ISSUE TITLE
TaskCanceledException

### ISSUE THREAD

**Issue by JoshKeegan** [JoshKeegan/KLog.NET#6]
1) Test Error : UnitTests.LogConcurrencyWrapperTests.TestUnderlyingLogDisposal
System.AggregateException : One or more errors occurred.
----> System.Threading.Tasks.TaskCanceledException : A task was canceled.
at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
at KLog.LogConcurrencyWrapper`1.BlockWhileWriting() in c:\projects\klog-net\KLog\KLog\LogConcurrencyWrapper.cs:line 106
at KLog.LogConcurrencyWrapper`1.Dispose(Boolean disposing) in c:\projects\klog-net\KLog\KLog\LogConcurrencyWrapper.cs:line 130
at UnitTests.LogConcurrencyWrapperTests.TestUnderlyingLogDisposal() in c:\projects\klog-net\KLog\UnitTests\LogConcurrencyWrapperTests.cs:line 26
--TaskCanceledException

Full build output at: https://ci.appveyor.com/project/JoshKeegan/klog-net/build/0.1.65

Looks like the task is being canceled before its actually finished starting up (entered the Running state).

**Comment by JoshKeegan** [comment]
Unit test failure is intermittent. On my machine, it will always pass in the VS test runner and fails sometimes in the NUnit test runner GUI
